[General]
user-interface = Cmdenv
# 使用 Cmdenv 模式运行仿真，避免打开图形界面
cmdenv-express-mode = true
# cmdenv-event-banners = true
cmdenv-message-trace = false
# cmdenv-message-trace = true  原先

# user-interface = Tkenv
# 打开图形界面


repeat = 1
# 设置重复模拟的次数。=1: 模拟将仅运行一次

seed-set = ${runnumber}
simtime-scale = -9
# =-6,  the simulation time scale is adjusted to microseconds 秒
# Precision is determined by a scale exponent, which is global (shared by all SimTime instances), and falls in the range -18..0. For example, a scale exponent of -6 means microsecond precision.
# 用于设置模拟的时间刻度。值 -12 表示时间的基本单位是皮秒（10^-12 秒）。这会影响时间的测量和呈现方式。
# 假设仿真中有一些事件在极短的时间间隔内发生，例如纳秒级别的事件。如果 simtime-scale 设置得过大（例如，设置为 -3 只支持毫秒精度），那么这些事件可能会被视为同时发生，影响仿真结果的精确性。
# 但是如果 simtime-scale 设置得足够精细（例如，默认的 -1 自动选择或 -9 表示纳秒级别），那么仿真系统能够正确区分这些事件的顺序和时间间隔，从而保证仿真结果的准确性。

sim-time-limit = 3.1s
#5s
# Simulation
**.simulationDuration = 3.0
#4.9
# 将模拟的持续时间设置为 8 秒。
# 10
# me: 1024 1step needs 30s   # originally: 4050
# 变量声明时可以添加@unit特性，并携带度量的单位。
# 例如:volatile int packetLength@unit(byte)=defult(4KB);  子类或者子模块的定义中，参数不能加入或不考虑数的@unit特性。https://www.cnblogs.com/Duxue/p/13777251.html

**.ttlInitial =30

# Traffic
**.lambda = 1
**.generation = 1
# **.generation = ${generation = 0}

warmup-period = 0s
#1s
# 是在开始收集果之前运行模拟的时间。
# 指定初始预热期的长度。属于模拟前 x 秒的结果将不会记录到输出向量中，并且不会计入输出标量的计算中。此选项对于稳态模拟很有用。默认值为 0 秒（无预热期，结果中考虑了仿真开始时的所有数据。）。


**.module-eventlog-recording = true
**.vector-recording = false
# **.vector-recording = true   原先


**.result-recording-modes = count, -mean, -max, -min
**.app.**.scalar-recording = false
**.routing.**.scalar-recording = false
**.scalar-recording = false

# **.app.**.scalar-recording = true 原先
# **.routing.**.scalar-recording = true 原先
# **.scalar-recording = true 原先

network = NetworkAll
# 指定要模拟的网络。这应该与 .ned 文件中定义的网络名称匹配。